---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dynatrace-operator
spec:
  interval: 5m
  chart:
    spec:
      version: "1.3.0"
      chart: dynatrace-operator
      sourceRef:
        kind: HelmRepository
        name: dynatrace
      interval: 60m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace