apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true

resources:
- ../../base/dynatrace-operator
- ../../base/prometheus
- ../../base/cert-manager
- namespace.yaml
- rbac.yaml

patches:
- target:
    kind: HelmRelease
    name: kube-prometheus-stack
    namespace: prometheus
  path: prometheus-values.yaml