apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true

resources:
- ../../base/prometheus

patches:
- target:
    kind: HelmRelease
    name: kube-prometheus-stack
    namespace: prometheus
  path: prometheus-values.yaml