apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: prometheus
spec:
  # chart:
  #   spec:
  #     version: "59.x"
  values:
    grafana:
      service:
        type: LoadBalancer